#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# If working in a google cloud environment, fetch secret environment variables and write to .env file
python /fetch_gcloud_secrets.py

# Populate the environment from .env (solution from:
# https://gist.github.com/judy2k/7656bfe3b322d669ef75364a46327836#gistcomment-3500331)
# Note: Variables in the .env file will overwrite environment variables that are already set.

touch .env

function export_envs() {
  local envFile=${1:-.env}
  local isComment='^[[:space:]]*#'
  local isBlank='^[[:space:]]*$'
  while IFS= read -r line; do
    [[ $line =~ $isComment ]] && continue
    [[ $line =~ $isBlank ]] && continue
    key=$(echo "$line" | cut -d '=' -f 1)
    value=$(echo "$line" | cut -d '=' -f 2-)
    eval "export ${key}=\"$(echo \${value})\""
  done < <( cat "$envFile" )
}

export_envs

# Execute the provided run CMD
exec "$@"
