# This workflow tests and releases a new version of the package, then publishes it to PyPi and the
# octue/octue-sdk-python Docker Hub repository.

name: Release

# Only trigger when a pull request into main branch is merged.
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-tests:
    if: "github.event.pull_request.merged == true"
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        python: [ 3.8 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          TEST_PROJECT_NAME: ${{ secrets.TEST_PROJECT_NAME }}
        run: tox -e py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - uses: actions/checkout@v2
    - name: Get package version
      run: echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.body }}
        draft: false
        prerelease: false

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Make package
        run: |
          python3 -m pip install --upgrade setuptools wheel
          python3 setup.py sdist bdist_wheel
      - name: Publish latest package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true

  docker:
    runs-on: ubuntu-latest
    needs: release
    timeout-minutes: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get package version
        run: echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          push: true
          tags: octue/octue-sdk-python:${{ env.PACKAGE_VERSION }}-slim,octue/octue-sdk-python:latest
